assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/xembly/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |-
  export PATH=${PATH}:$(pwd)/../.local/bin
  pip3 install --upgrade pip
  pip3 install aibolit==1.2.3rc2
  pdd --source=$(pwd) --file=/dev/null
  aibolit check --folder=src/main
merge:
  script: |-
    mvn clean install -Pxembly -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml -Dinvoker.skip
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pxembly -Psonatype --errors --settings ../settings.xml
    # mvn clean site-deploy -Pxembly -Psite --errors --settings ../settings.xml -Dinvoker.skip
