# SPDX-FileCopyrightText: Copyright (c) 2013-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/xembly/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
install: |-
  pdd --source=$(pwd) --file=/dev/null
  export PATH=${PATH}:$(pwd)/../.local/bin
  # pip3 install --upgrade pip
  # pip3 install aibolit==1.2.3rc2
  # aibolit check --folder=src/main
merge:
  script: |-
    mvn clean install -Pxembly -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml -Dinvoker.skip
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    export MAVEN_OPTS="--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"
    mvn clean deploy -Pxembly -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Pxembly -Psite --errors --settings ../settings.xml -Dinvoker.skip || echo 'no site this time'
