# SPDX-FileCopyrightText: 2013-2025 Yegor Bugayenko <yegor256@gmail.com>
# SPDX-License-Identifier: MIT
---
name: infer
'on':
  push:
    branches:
      - master
jobs:
  infer:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: srz-zumix/setup-infer@v1
        with:
          infer_version: v1.0.0
      - run: infer --version
      - run: infer run --fail-on-issue --no-progress-bar -- mvn test
