# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2013-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: ort
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ort:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          fail-on: 'violations'
