# SPDX-FileCopyrightText: Copyright (c) 2013-2025 Yegor Bugayenko <yegor256@gmail.com>
# SPDX-License-Identifier: MIT
---
name: reuse
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  reuse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v5
