# SPDX-FileCopyrightText: Copyright (c) 2013-2025 Yegor Bugayenko <yegor256@gmail.com>
# SPDX-License-Identifier: MIT
---
name: xcop
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/xcop-action@master
